// Generated by tools/version.js from package.json. Do not edit by hand.
export const RUNTIME_METADATA = Object.freeze({
  version: "1.0.0",
  channel: "stable",
  minimumBedrock: "1.21.0",
  scriptApi: "1.13.0",
  serverUiApi: "1.3.0"
});
